routes/web.php
		Route::get('/pilih-anjab', 'AbkController@pilihAnjab')->name('abk.pilih-anjab');
		Route::post('/simpan', 'AbkController@save')->name('abk.save-abk');
		Route::post('/update', 'AbkController@update')->name('abk.update-abk');
		Route::post('/delete', 'AbkController@deleteAbk')->name('abk.delete-abk');
		Route::post('/verif', 'AbkController@verifikasiStrukturalPelaksana')->name('abk.verifikasi-abk-struktural-pelaksana');
		Route::get('/detail/{id}', 'AbkController@detail')->name('abk.detail');
		Route::get('/{jenis}', 'AbkController@browse')->name('abk.browse');
		Route::post('/delete-abk-khusus', 'AbkController@deleteAbkKhusus')->name('abk.delete-abk-khusus');
		Route::post('/verif-khusus', 'AbkController@verifikasi')->name('abk.verifikasi-abk-khusus');
		Route::post('/batalverif-khusus', 'AbkController@batalverifikasi')->name('abk.batal-verifikasi-abk-khusus');
		Route::get('/cek-relasi', 'AbkController@cekRelasi')->name('anjab.cek-relasi');
		
	});



	Route::group(['prefix'=>'komjab'], function(){

		Route::get('pilih-anjab', 'KomjabController@pilihAnjab')->name('komjab.pilih-anjab');
		Route::get('/get-data', 'KomjabController@getData')->name('komjab.get-data');
		Route::get('/get-form', 'KomjabController@getForm')->name('komjab.get-form');
		Route::get('/get-data/teknis', 'KomjabController@getDataTeknis')->name('komjab.get-data-teknis');
		Route::post('/save', 'KomjabController@save')->name('komjab.save');
		Route::post('/update', 'KomjabController@save')->name('komjab.update');
		Route::post('/delete', 'KomjabController@delete')->name('komjab.delete');
		Route::get('/{jenis}', 'KomjabController@browse')->name('komjab.browse');
		Route::get('detail/{id}', 'KomjabController@detail')->name('komjab.detail');
		Route::get('/print-word/{id_komjab}', 'KomjabController@printWord')->name('komjab.print-word');

		// Route::post('/save', 'AnjabInputKomjabController@save')->name('komjab.save');
		// Route::post('/update', 'AnjabInputKomjabController@save')->name('komjab.update');
		// Route::get('/get-data', 'AnjabInputKomjabController@getData')->name('komjab.get-data');
		// Route::get('/get-form', 'AnjabInputKomjabController@getForm')->name('komjab.get-form');
		// Route::get('/get-data/teknis', 'AnjabInputKomjabController@getDataTeknis')->name('komjab.get-data-teknis');
		// Route::post('/save', 'AnjabInputKomjabController@save')->name('komjab.save');
		// Route::post('/update', 'AnjabInputKomjabController@save')->name('komjab.update');
		// Route::post('/delete', 'AnjabInputKomjabController@delete')->name('komjab.delete');
		// Route::get('/print-word/{id_komjab}', 'AnjabInputKomjabController@printWord')->name('komjab.print-word');
		// Route::get('/{id}', 'AnjabInputKomjabController@input')->name('komjab.input');
	});

	Route::group(['prefix'=>'jabatan'], function(){

		Route::group(['prefix'=>'struktural'], function(){
			Route::get('/', 'JabatanStrukturalController@browse')->name('jabatan-struktural.browse');
			Route::get('/get-form', 'JabatanStrukturalController@getForm')->name('jabatan-struktural.get-form');
			Route::post('/save', 'JabatanStrukturalController@save')->name('jabatan-struktural.save');
			Route::post('/delete', 'JabatanStrukturalController@delete')->name('jabatan-struktural.delete');
		});
		Route::group(['prefix'=>'fungsional'], function(){
			Route::get('/', 'JabatanFungsionalController@browse')->name('jabatan-fungsional.browse');
			Route::get('/get-form', 'JabatanFungsionalController@getForm')->name('jabatan-fungsional.get-form');
			Route::get('/detail/{id}', 'JabatanFungsionalController@detail')->name('jabatan-fungsional.detail');
			Route::post('/save', 'JabatanFungsionalController@save')->name('jabatan-fungsional.save');
			Route::post('/delete', 'JabatanFungsionalController@delete')->name('jabatan-fungsional.delete');
			Route::post('/delete-jabatan', 'JabatanFungsionalController@deleteJenjang')->name('jabatan-fungsional.delete-jenjang');
			Route::post('/delete-syarat', 'JabatanFungsionalController@deleteSyarat')->name('jabatan-fungsional.delete-syarat');
		});
		Route::group(['prefix'=>'pelaksana'], function(){
			Route::get('/', 'JabatanPelaksanaController@browse')->name('jabatan-pelaksana.browse');
			Route::get('/get-form', 'JabatanPelaksanaController@getForm')->name('jabatan-pelaksana.get-form');
			Route::post('/save', 'JabatanPelaksanaController@save')->name('jabatan-pelaksana.save');
			Route::post('/delete', 'JabatanPelaksanaController@delete')->name('jabatan-pelaksana.delete');
		});
		Route::group(['prefix'=>'upt'], function(){
			Route::get('/', 'JabatanUptController@browse')->name('jabatan-upt.browse');
			Route::get('/get-form', 'JabatanUptController@getForm')->name('jabatan-upt.get-form');
			Route::post('/save', 'JabatanUptController@save')->name('jabatan-upt.save');
			Route::post('/delete', 'JabatanUptController@delete')->name('jabatan-upt.delete');
		});
	});
	Route::group(['prefix'=>'fungsi-pekerjaan'], function(){
		Route::get('/', 'FungsiPekerjaanController@browse')->name('fungsi-pekerjaan.browse');
		Route::get('/get-form', 'FungsiPekerjaanController@getForm')->name('fungsi-pekerjaan.get-form');
		Route::post('/save', 'FungsiPekerjaanController@save')->name('fungsi-pekerjaan.save');
		Route::post('/delete', 'FungsiPekerjaanController@delete')->name('fungsi-pekerjaan.delete');
	});
	Route::group(['prefix'=>'minat-kerja'], function(){
		Route::get('/', 'MinatKerjaController@browse')->name('minat-kerja.browse');
		Route::get('/get-form', 'MinatKerjaController@getForm')->name('minat-kerja.get-form');
		Route::post('/save', 'MinatKerjaController@save')->name('minat-kerja.save');
		Route::post('/delete', 'MinatKerjaController@delete')->name('minat-kerja.delete');
	});
	Route::group(['prefix'=>'instansi-pembina'], function(){
		Route::get('/', 'InstansiPembinaController@browse')->name('instansi-pembina.browse');
		Route::get('/get-form', 'InstansiPembinaController@getForm')->name('instansi-pembina.get-form');
		Route::post('/save', 'InstansiPembinaController@save')->name('instansi-pembina.save');
		Route::post('/delete', 'InstansiPembinaController@delete')->name('instansi-pembina.delete');
	});
	Route::group(['prefix'=>'tempramen-kerja'], function(){
		Route::get('/', 'TempramenKerjaController@browse')->name('tempramen-kerja.browse');
		Route::get('/get-form', 'TempramenKerjaController@getForm')->name('tempramen-kerja.get-form');
		Route::post('/save', 'TempramenKerjaController@save')->name('tempramen-kerja.save');
		Route::post('/delete', 'TempramenKerjaController@delete')->name('tempramen-kerja.delete');
	});
	Route::group(['prefix'=>'unit-kerja'], function(){
		Route::get('/', 'UnitKerjaController@browse')->name('unit-kerja.browse');
		Route::get('/get-form', 'UnitKerjaController@getForm')->name('unit-kerja.get-form');
		Route::post('/save', 'UnitKerjaController@save')->name('unit-kerja.save');
		Route::post('/delete', 'UnitKerjaController@delete')->name('unit-kerja.delete');
	});
	Route::group(['prefix'=>'bakat-kerja'], function(){
		Route::get('/', 'BakatKerjaController@browse')->name('bakat-kerja.browse');
		Route::get('/get-form', 'BakatKerjaController@getForm')->name('bakat-kerja.get-form');
		Route::post('/save', 'BakatKerjaController@save')->name('bakat-kerja.save');
		Route::post('/delete', 'BakatKerjaController@delete')->name('bakat-kerja.delete');
	});
	Route::group(['prefix'=>'upaya-fisik'], function(){
		Route::get('/', 'UpayaFisikController@browse')->name('upaya-fisik.browse');
		Route::get('/get-form', 'UpayaFisikController@getForm')->name('upaya-fisik.get-form');
		Route::post('/save', 'UpayaFisikController@save')->name('upaya-fisik.save');
		Route::post('/delete', 'UpayaFisikController@delete')->name('upaya-fisik.delete');
	});
	Route::group(['prefix'=>'users'], function(){
		Route::get('/', 'UserController@browse')->name('user.browse');
		Route::get('/get-form', 'UserController@getForm')->name('user.get-form');
		Route::get('/get-pegawai-from-simpeg', 'UserController@getPegawaiFromSimpeg')->name('user.get-pegawai-from-simpeg');
		Route::get('/get-pegawai-satker-from-simpeg', 'UserController@getPegawaiSatkerFromSimpeg')->name('user.get-pegawai-satker-from-simpeg');
		Route::post('/save', 'UserController@save')->name('user.save');
		Route::post('/delete', 'UserController@delete')->name('user.delete');
		
		Route::get('/cek', 'UserController@getdb');
	});

	Route::group(['prefix'=>'periode'], function(){
		Route::get('/', 'PeriodeController@browse')->name('periode.browse');
		Route::get('/get-form', 'PeriodeController@getForm')->name('periode.get-form');
		Route::post('/save', 'PeriodeController@save')->name('periode.save');
		Route::post('/delete', 'PeriodeController@delete')->name('periode.delete');
	});

	Route::get('/compare-data', function(){
		$jabatanBkpp = \App\Models\MJabatanBkpp::all();

		foreach($jabatanBkpp as $itemJabatanBkpp){
			$jabatan = \App\Models\MJabatan::whereRaw('LOWER(nama) = ?', strtolower($itemJabatanBkpp->nama_jabatan))->first();
			if($jabatan){
				echo $jabatan->nama;
				$jabatan->kode_jabatan = $itemJabatanBkpp->kode_jabatan;
				$jabatan->update();
			}else{
				$newJabatan = new \App\Models\MJabatan();
				$newJabatan->nama = $itemJabatanBkpp->nama_jabatan;
				$newJabatan->kode_jabatan = $itemJabatanBkpp->kode_jabatan;
				if($itemJabatanBkpp->jenis == 'JST'){
					$newJabatan->jenis_jabatan = 'struktural';
				}elseif($itemJabatanBkpp->jenis == 'JFU'){
					$newJabatan->jenis_jabatan = 'pelaksana';
				}elseif($itemJabatanBkpp->jenis == 'JFT'){
					$newJabatan->jenis_jabatan = 'fungsional';
				}

				$newJabatan->save();
			}
		}

	});

	Route::group(['prefix'=>'laporan'], function(){
		Route::group(['prefix'=>'rekap-kelas-jabatan'], function(){
			Route::get('/', 'LaporanController@browseKelasJabatan')->name('laporan.rekap-kelas-jabatan.browse');
		});
		Route::group(['prefix'=>'rekap-jabatan-struktural'], function(){

app/Models/MJabatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MJabatan extends Model
{

    use SoftDeletes;
    
    protected $table = 'm_jabatan_struktural';

    function dataAnjab(){
    	return $this->belongsTo('App\Models\TrxAnjab', 'id', 'm_jabatan_id');
    }

    function getKodeAttribute($value){
        if($this->jenis == 'pelaksana'){
            return $this->kode_urusan_pemerintahan.'-'.$value;
        }else{
            return $value;
        }
    }

    function getTextDasarHukumAttribute(){
    	$dasarHukum = $this->attributes['dasar_hukum'];

    	if($dasarHukum == 'sk-bupati-315-2020'){
    		return 'KEPUTUSAN BUPATI MOJOKERTO NOMOR 188.45/315/HK/416-012/2020 TAHUN 2020';
    	}else{
    		return 'Tidak Ada Aturan';
    	}
    }
}

resources/views/master/jabatan-fungsional/browse.blade.php
@extends('layout')

@section('content')
<style type="text/css">
  #anjab_tabel_filter{
    text-align: right;
  }
</style>
<!--begin::Page Vendors Styles(used by this page)-->
<link href="{{ asset('') }}assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
<!--end::Page Vendors Styles-->
<!--begin::Container-->
              <div class="container">
                <!--begin::Dashboard-->
                <!--begin::Card-->
                <div class="card card-custom">
                  <div class="card-header flex-wrap py-5">
                    <div class="card-title">
                      <h3 class="card-label">{{ isset($page) ? $page : 'Dashboard' }}
                      <div class="text-muted pt-2 font-size-sm">Data {{ isset($page) ? $page : 'Dashboard' }}</div></h3>
                    </div>
                    <div class="card-toolbar">
                      <!--begin::Button-->
                      <a href="javascript:;" class="btn btn-primary btn-sm font-weight-bolder add-jabatan">
                       <i class="far fa-plus-square"></i>Tambah Jabatan</a>
                      <!--end::Button-->
                    </div>
                  </div>
                  <div class="card-body">
                    <!--begin: Datatable-->
                    <table class="table table-separate table-head-custom table-foot-custom table-checkable" id="kt_datatable" style="margin-top: 13px !important">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kode Jabatan</th>
                                <th>Nama Jabatan</th>
                                <th>Rumpun</th>
                                <th>Ikhtisar</th>
                                <th>Instansi Pembina</th>
                                <th>Kategori</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                           @foreach($jabatan as $itemJabatan)
                           <tr>
                             <td>{{ $loop->iteration }}</td>
                             <td>{{ $itemJabatan->_kode }}</td>
                             <td>{{ ucwords(strtolower($itemJabatan->jabatan)) }}</td>
                             <td>{{ @$itemJabatan->dataRumpun->rumpun }}</td>
                             <td>{{ $itemJabatan->tugas }}</td>
                             <td>{{ @$itemJabatan->dataInstansiPembina->nama }}</td>
                             <td>
                                @if ($itemJabatan->kategori == "ketrampilan")
                                    <p><span class="badge badge-primary" style="width:100px" >Ketrampilan</span></p>
                                @elseif ($itemJabatan->kategori == "keahlian")
                                    <p><span class="badge badge-success" style="width:100px">Keahlian</span></p>
                                @elseif ($itemJabatan->kategori == "ketrampilan_keahlian")
                                    <p><span class="badge badge-warning" style="width:100px">Ketrampilan <br>& Keahlian</span></p>
                                @endif
                             </td>
                             <td>
                               <div class="btn-group dropleft">
                                  <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Menu
                                  </button>
                                  <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">
                                    <!--begin::Naviigation-->
                                    <ul class="navi">

                                      <li class="navi-item">
                                        <a href="{{ route('jabatan-fungsional.detail', $itemJabatan->id) }}" class="navi-link">
                                          <span class="navi-icon">
                                            <i class="navi-icon flaticon-edit-1"></i>
                                          </span>
                                          <span class="navi-text">Detail</span>
                                        </a>
                                      </li>

                                      <li class="navi-item">
                                        <a data-id="{{ $itemJabatan->id }}"  href="javascript:;" class="navi-link edit-jabatan">
                                          <span class="navi-icon">
                                            <i class="navi-icon flaticon-edit-1"></i>
                                          </span>
                                          <span class="navi-text">Edit</span>
                                        </a>
                                      </li>

                                      <li class="navi-item">
                                        <a data-id="{{ $itemJabatan->id }}"  href="javascript:;" class="navi-link delete-jabatan">
                                          <span class="navi-icon">
                                            <i class="navi-icon flaticon-delete-1"></i>
                                          </span>
                                          <span class="navi-text">Hapus</span>
                                        </a>
                                      </li>
                                    </ul>
                                    <!--end::Naviigation-->
                                  </div>
                              </div>
                             </td>
                           </tr>
                           @endforeach
                          </tbody>
                        <tfoot>
                            <tr>
                                <th>No</th>
                                <th>Kode Jabatan</th>
                                <th>Nama Jabatan</th>
                                <th>Rumpun</th>
                                <th>Tugas Jabatan</th>
                                <th>Instansi Pembina</th>
                                <th>Kategori</th>
                                <th>Aksi</th>
                            </tr>
                        </tfoot>
                    </table>
                    <!--end: Datatable-->
                  </div>
                </div>
                <!--end::Card-->

                <!--end::Dashboard-->
              </div>
              <!--end::Container-->

            <div id="modal-jabatan" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
              <div class="modal-dialog modal-md">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <form method="POST" action="{{ route('jabatan-fungsional.save') }}">
                    {{ csrf_field() }}
                    <div class="modal-body">

                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-link btn-sm" data-dismiss="modal">Batal</button>
                      <button type="submit" class="btn btn-primary btn-sm">Simpan <i class="icon-paperplane"></i></button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

          <form id="form-delete-jabatan" method="POST" action="{{ route('jabatan-fungsional.delete') }}">
            {{ csrf_field() }}
            <input type="hidden" value="" name="id">
          </form>
@endsection

@section('js')
{{-- js files --}}
<script src="{{ asset('') }}/assets/js/pages/crud/forms/widgets/select2.js"></script>
{{-- end js files --}}

@endsection

@section('page-script')
<script type="text/javascript">
  initEdit();
  initHapus();

  $('.add-jabatan').on('click', function(){
    $.ajax({
      url:'{{ route('jabatan-fungsional.get-form') }}',
      method:'GET',
      data:{aksi:'create-jabatan'},
      success:function(result){
        $('#modal-jabatan .modal-title').text("Tambah Jabatan");
        $('#modal-jabatan .modal-body').html(result);
        $('#modal-jabatan').modal('show');
        $('.select2').select2();
      }
    });
  });

  function initEdit(){
    $('.edit-jabatan').on('click', function(){
      var id = $(this).data('id');
      $.ajax({
        url:'{{ route('jabatan-fungsional.get-form') }}',
        method:'GET',
        data:{aksi:'edit-jabatan',id:id },
        success:function(result){
          $('#modal-jabatan .modal-title').text("Edit Jabatan");
          $('#modal-jabatan .modal-body').html(result);
          $('#modal-jabatan').modal('show');
          $('.select2').select2();
        }
      });
    });
  }

  function initHapus(){
    $('.delete-jabatan').on('click', function(){
      var id = $(this).data('id');
          swal.fire({
              title: 'Apakah anda yakin?',
              text: "Data yang sudah dihapus, tidak dapat dikembalikan",
              type: 'warning',
              showCancelButton: true,
              confirmButtonText: 'Hapus Data',
              cancelButtonText: 'Batal',
              confirmButtonClass: 'btn btn-success',
              cancelButtonClass: 'btn btn-warning',
              buttonsStyling: false
          }).then(function (status) {
            if(status.value){
              $('form[id=form-delete-jabatan] input[name=id]').val(id);
                  $('form[id=form-delete-jabatan').submit();
            }
          });
    });
  }

</script>
<!--begin::Page Vendors(used by this page)-->
<script src="{{ asset('') }}assets/plugins/custom/datatables/datatables.bundle.js"></script>
<!--end::Page Vendors-->
<!--begin::Page Scripts(used by this page)-->
<script src="{{ asset('') }}assets/js/pages/crud/datatables/advanced/row-callback.js"></script>
<!--end::Page Scripts-->
@endsection

resources/views/master/jabatan-fungsional/form-create-jenjang.blade.php
<div class="row">
	<div class="col-12">
		<input type="hidden" value="add-jenjang" name="aksi">

		<div class="form-group">
			{{-- <label>Kode Jabatan</label> --}}
			<input class="form-control" type="hidden" name="id_m_jabatan_fungsional" value="{{ $jabatan->id }}" required="">
			<input class="form-control" type="hidden" name="kode_jabatan" value="{{ $jabatan->kode_jabatan }}" required="">
		</div>

        <div class="form-group">
			<label>Jenjang</label>
			<select class="form-control" name="jenjang">
				<option selected="" disabled="">-- PILIH Jenjang --</option>
				@foreach(\MojokertokabApp::getJenjangFungsional() as $key => $itemjenjang)
				<option value="{{ $key }}">{{ $itemjenjang }}</option>
				@endforeach
				
				<!-- <option value="pemula">Pemula</option>
				<option value="pelaksana_pemula">Pelaksana Pemula</option>
				<option value="terampil">Terampil</option>
				<option value="pelaksana">Pelaksana</option>
				<option value="mahir">Mahir</option>
				<option value="pelaksana_lanjutan">Pelaksana Lanjutan</option> -->
				<!-- <option value="pemula_pelaksana_emula">Pemula/Pelaksana Pemula</option>
				<option value="terampil_pelaksana">Terampil/Pelaksana</option>
				<option value="mahir_pelaksana_lanjutan">Mahir/Pelaksana Lanjutan</option> -->
				<!-- <option value="penyelia">Penyelia</option>
				<option value="pertama">Pertama</option>
				<option value="muda">Muda</option>
				<option value="madya">Madya</option>
				<option value="utama">Utama</option>
				<option value="ahli_pertama">Ahli Pertama</option>
				<option value="ahli_muda">Ahli Muda</option>
				<option value="ahli_madya">Ahli Madya</option>
				<option value="ahli_utama">Ahli Utama</option> -->
			</select>
		</div>

        <div class="form-group">
			<label>Golru</label>
			<select class="form-control" name="golru">
				<option selected="" disabled="">-- PILIH Golongan/Ruang --</option>
				<option value="II/A">II/A</option>
				<option value="II/B">II/B</option>
				<option value="II/C">II/C</option>
				<option value="II/D">II/D</option>
				<option value="III/A">III/A</option>
				<option value="III/B">III/B</option>
				<option value="III/C">III/C</option>
				<option value="III/D">III/D</option>
				<option value="IV/A">IV/A</option>
				<option value="IV/B">IV/B</option>
				<option value="IV/C">IV/C</option>
				<option value="IV/D">IV/D</option>
			</select>
		</div>

		<div class="form-group">
			<label>Angka Kredit</label>
            <input class="form-control" type="text" name="angka_kredit" required="">
		</div>

	</div>

</div>

resources/views/master/jabatan-fungsional/form-create-syarat.blade.php
<div class="row">
	<div class="col-12">
		<input type="hidden" value="add-syarat" name="aksi">

		<div class="form-group">
			{{-- <label>Kode Jabatan</label> --}}
			<input class="form-control" type="hidden" name="id_m_jabatan_fungsional" value="{{ $jabatan->id }}" required="">
			<input class="form-control" type="hidden" name="kode_jabatan" value="{{ $jabatan->kode_jabatan }}" required="">
		</div>

        <div class="form-group">
			<label>Pendidikan</label>
			{{-- <select class="form-control" name="pendidikan">
				<option selected="" disabled="">-- PILIH Pendidikan --</option>
				<option value="SMA">SMA</option>
				<option value="D1">D1</option>
				<option value="D2">D2</option>
				<option value="D3">D3</option>
				<option value="D4">D4</option>
				<option value="S1">S1</option>
				<option value="S2">S2</option>
				<option value="S3">S3</option>
				<option value="S1/D4">S1/D4</option>
			</select> --}}
            <input class="form-control" type="text" name="pendidikan" placeholder="Masukkan Pendidikan" required="">
		</div>

	</div>

</div>

resources/views/master/jabatan-fungsional/form-create.blade.php
<div class="row">
	<div class="col-12">
		<input type="hidden" value="add-jabatan" name="aksi">

		<div class="form-group">
			<label>Nama</label>
			<input class="form-control" type="text" name="nama" required="">
		</div>

		<div class="form-group">
			<label>Rumpun Jabatan</label>
			<select class="form-control" name="rumpun">
				<option selected="" disabled="">-- PILIH Rumpun --</option>
				@foreach($rumpun as $itemRumpun)
				<option value="{{ $itemRumpun->kode }}">{{ $itemRumpun->rumpun }}</option>
				@endforeach
			</select>
		</div>

		<div class="form-group">
			<label>Ikhtisar</label>
			<textarea class="form-control" name="tugas"></textarea>
		</div>

		<div class="form-group">
			<label>Instansi Pembina</label>
			<select class="form-control" name="instansi_pembina">
				<option selected="" disabled="">-- PILIH Instansi Pembina --</option>
				@foreach($instansiPembina as $itemInstansiPembina)
				<option value="{{ $itemInstansiPembina->id }}">{{ $itemInstansiPembina->nama }}</option>
				@endforeach
			</select>
		</div>

        <div class="form-group">
			<label>Kategori</label>
			<select class="form-control" name="kategori">
				<option selected="" disabled="">-- PILIH Kategori --</option>
				<option value="keahlian">Keahlian</option>
				<option value="ketrampilan">Ketrampilan</option>
				<option value="ketrampilan_keahlian">Ketrampilan & Keahlian</option>
			</select>
		</div>

	</div>

</div>

resources/views/master/jabatan-fungsional/form-edit.blade.php
<div class="row">
	<div class="col-12">
		<input type="hidden" value="update-jabatan" name="aksi">
		<input type="hidden" value="{{ $jabatan->id }}" name="id">

		<div class="form-group">
			<label>Nama</label>
			<input class="form-control" type="text" name="nama" value="{{ $jabatan->jabatan }}" required="">
		</div>

		<div class="form-group">
			<label>Rumpun Jabatan</label>
			<select class="form-control" name="rumpun">
				<option selected="" disabled="">-- PILIH Rumpun --</option>
				@foreach($rumpun as $itemRumpun)
				<option value="{{ $itemRumpun->kode }}" @if($itemRumpun->id == $jabatan->m_jabatan_fungsional_rumpun_id) selected @endif>{{ $itemRumpun->rumpun }}</option>
				@endforeach
			</select>
		</div>

		<div class="form-group">
			<label>Tugas</label>
			<textarea class="form-control" name="tugas" rows="5">{{ $jabatan->tugas }}</textarea>
		</div>

		<div class="form-group">
			<label>Instansi Pembina</label>
			<select class="form-control" name="instansiPembina">
				<option selected="" disabled="">-- PILIH Instansi Pembina --</option>
				@foreach($instansiPembina as $itemInstansiPembina)
				<option value="{{ $itemInstansiPembina->id }}" @if($itemInstansiPembina->id == $jabatan->m_jabatan_fungsional_instansi_pembina_id) selected @endif>{{ $itemInstansiPembina->nama }}</option>
				@endforeach
			</select>
		</div>

        <div class="form-group">
			<label>Kategori</label>
			<select class="form-control" name="kategori">
				<option value="keahlian" @if ($jabatan->kategori == "keahlian") selected @endif>Keahlian</option>
				<option value="ketrampilan" @if ($jabatan->kategori == "ketrampilan") selected @endif>Ketrampilan</option>
				<option value="ketrampilan_keahlian" @if ($jabatan->kategori == "ketrampilan_keahlian") selected @endif>Ketrampilan & Keahlian</option>
			</select>
		</div>

	</div>

</div>